# Generated by Django 4.2.3 on 2023-08-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
