# Generated by Django 4.2.3 on 2023-08-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
